baseurl = "https://quiescent.us/"
languageCode = "en-us"
enableRobotsTXT = true
title = "The Quiescent Current"
copyright = "©2022 Jeremy Wright"

disqusShortname = "codestrokes2"
pygmentsuseclasses = true
theme="minimal-bootstrap-hugo-theme"

[taxonomies]
  series = "series"
  tag = "tags"
  language = "languages"
  project = "projects"

[permalinks]
    posts = "/:year/:month/:slug/"

[params]
	sidebartitle="The Quiescent Current"
	style="light"
	dateFormat="Monday, January 2, 2006"
	slogan="Go Far. Go Together."
  GoogleAnalytics="UA-168773592-1"
	description = "Some description"
	contentBackgroundColor = "#fff"
	contentTextColor = "#212529"
	contentLinkColor = "#007bff"
	contentLinkHoverColor = "#0056b3"
	navbarBackgroundColor = "#212529"
	navbarLinkColor = "rgba(255, 255, 255, 0.75)"
	navbarLinkHoverColor = "rgba(255, 255, 255, 1)"
	wrapperMaxWidth = "800px"
	customDateFormat = "Jan 2, 2006"
	customCodeStyle = true
	customBlockquoteStyle = true
	showPostSummary = false
	googleAnalytics = "UA-123456789-1"
	cookieConsent = true
	includeBootstrapJs = false
	faviconSafariPinnedTabColor = "#5bbad5"
	faviconMsApplicationTileColor = "#da532c"
	faviconThemeColor = "#ffffff"

[params.math]
    enable = true  
    use = "katex"  # option: "katex", "mathjax". default: "katex"

[menu]
  [[Menus.nav]]
  Name = "Posts"
  url = "/posts"
  weight = 1
  [[Menus.nav]]
  Name = "Series"
  url = "/series"
  weight = 2
  [[Menus.nav]]
  Name = "Tags"
  url = "/tags"
  weight = 2
  [[Menus.nav]]
  Name = "About"
  url = "/about"
  weight = 4

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "lovelace"
    tabWidth = 2
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2
