baseurl = "https://quiescent.us/"
languageCode = "en-us"
enableRobotsTXT = true
title = "The Quiescent Current"
copyright = "©2020 Jeremy Wright"

disqusShortname = "codestrokes2"
pygmentsuseclasses = true
theme="hugo-notepadium"
[permalinks]
    posts = "/:year/:month/:slug/"

[markup.highlight]
codeFences = true
noClasses = false

[params]
	sidebartitle="The Quiescent Current"
	style="light"
	dateFormat="Monday, January 2, 2006"
	slogan="Go Far. Go Together."
    GoogleAnalytics="UA-168773592-1"
    highlightStyle = "docco"

[params.share]
	enable = true
	addThisId = "ra-1234567890"
	inlineToolId = ""

[params.comments]
	enable=false

[params.profile]
  enable = false
  avatar = "/img/avatar.jpg"
  name = "Jeremy Wright"
  bio = "[About Me](/about/)"  # support markdown syntax
  github = "JeremyLWright"  # https://github.com/XXX

[params.nav]
	showCategories = true
	showTags = true

[[params.nav.custom]]
	title = "Blog"
	url = "/posts"

[[menu.main]]
	name = "Series"
	url = "/series"

[[params.nav.custom]]
	title = "About"
	url = "/about"

[[menu.footer]]
    name = "Blog"
    url = "/posts"
	
[[menu.footer]]
    name = "Series"
	url = "/series"

[[menu.social]]
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/JeremyLWright"
    identifier = "github"

[[menu.social]]
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://www.twitter.com/jeremy_l_wright"
    identifier = "twitter"

[[menu.social]]
    pre = "<i class='fa fa-linkedin'></i>"
    url = "https://www.linkedin.com/pub/jeremy-wright/5b/8/844"
    identifier = "linkedin"
