baseurl = "https://quiescent.us/"
languageCode = "en-us"
title = "QE"
disqusShortname = "codestrokes2"
pygmentsuseclasses = true
theme="redlounge"
[permalinks]
    posts = "/:year/:month/:slug/"

[params]
	sidebartitle="Quiescent Engineering, LLC"
	sidebartagline="Go Far. Go Together"
    GoogleAnalytics="UA-168773592-1"
    highlightStyle = "docco"

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[[menu.main]]
	name = "Blog"
	url = "/posts"

[[menu.main]]
	name = "Series"
	url = "/series"

[[menu.main]]
	name = "About"
	url = "/about"

[[menu.footer]]
    name = "Blog"
    url = "/posts"
	
[[menu.footer]]
    name = "Series"
	url = "/series"

[[menu.social]]
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/JeremyLWright"
    identifier = "github"

[[menu.social]]
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://www.twitter.com/jeremy_l_wright"
    identifier = "twitter"

[[menu.social]]
    pre = "<i class='fa fa-linkedin'></i>"
    url = "https://www.linkedin.com/pub/jeremy-wright/5b/8/844"
    identifier = "linkedin"
